package com.cplatform.back.classroom.entity;

import java.util.Date;

public class Classroom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom.school_id
     *
     * @mbggenerated
     */
    private String schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom.classroom_name
     *
     * @mbggenerated
     */
    private String classroomName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom.capacity
     *
     * @mbggenerated
     */
    private String capacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom.nfc_id
     *
     * @mbggenerated
     */
    private String nfcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom.floor_numb
     *
     * @mbggenerated
     */
    private String floorNumb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom.building_numb
     *
     * @mbggenerated
     */
    private String buildingNumb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom.projector
     *
     * @mbggenerated
     */
    private Integer projector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    private String schoolName;

    public String getSchoolName() {
        return schoolName;
    }

    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classroom
     *
     * @mbggenerated
     */
    public Classroom(Integer id, String schoolId, String classroomName, String capacity, String nfcId, String floorNumb, String buildingNumb, Integer projector, Date createTime, Date updateTime) {
        this.id = id;
        this.schoolId = schoolId;
        this.classroomName = classroomName;
        this.capacity = capacity;
        this.nfcId = nfcId;
        this.floorNumb = floorNumb;
        this.buildingNumb = buildingNumb;
        this.projector = projector;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom.id
     *
     * @return the value of t_classroom.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom.school_id
     *
     * @return the value of t_classroom.school_id
     * @mbggenerated
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom.classroom_name
     *
     * @return the value of t_classroom.classroom_name
     * @mbggenerated
     */
    public String getClassroomName() {
        return classroomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom.capacity
     *
     * @return the value of t_classroom.capacity
     * @mbggenerated
     */
    public String getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom.nfc_id
     *
     * @return the value of t_classroom.nfc_id
     * @mbggenerated
     */
    public String getNfcId() {
        return nfcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom.floor_numb
     *
     * @return the value of t_classroom.floor_numb
     * @mbggenerated
     */
    public String getFloorNumb() {
        return floorNumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom.building_numb
     *
     * @return the value of t_classroom.building_numb
     * @mbggenerated
     */
    public String getBuildingNumb() {
        return buildingNumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom.projector
     *
     * @return the value of t_classroom.projector
     * @mbggenerated
     */
    public Integer getProjector() {
        return projector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom.create_time
     *
     * @return the value of t_classroom.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom.update_time
     *
     * @return the value of t_classroom.update_time
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }
}